test website is up after push

diff --git a/.github/workflows/opw-prod.yml b/.github/workflows/opw-prod.yml
--- a/.github/workflows/opw-prod.yml
+++ b/.github/workflows/opw-prod.yml
@@ -52,18 +52,15 @@ jobs:
           count=0
           max_attempts=30
           while true; do
-            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.PRODUCTION_SERVER }}:8069)
-            if [ $status_code -eq 200 ]; then
-              echo "Website is up."
+            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.PRODUCTION_SERVER }}:8069 || echo "Curl failed")
+            if [ "$status_code" = "200" ]; then
               break
             else
               count=$((count+1))
-              echo "Attempt $count: Website is not up, retrying..."
               if [ $count -ge $max_attempts ]; then
-                echo "Website is not up after $max_attempts attempts, stopping."
                 exit 1
               fi
-              sleep 1
+              sleep 5
             fi
           done
         shell: bash
