test website is up after push

diff --git a/.github/workflows/opw-testing.yml b/.github/workflows/opw-testing.yml
--- a/.github/workflows/opw-testing.yml
+++ b/.github/workflows/opw-testing.yml
@@ -48,9 +48,9 @@ jobs:
           max_attempts=30
           while true; do
             echo "Attempt $count: "
-            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.TESTING_SERVER }}:8069)
+            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.TESTING_SERVER }}:8069 || echo "Curl failed")
             echo "Received status code $status_code"
-            if [ $status_code -eq 200 ]; then
+            if [ "$status_code" = "200" ]; then
               echo "Website is up."
               break
             else
